### ISSUE TITLE
Add a test for `pytensor.config.blas__ldflags` that only runs on the full pytensor recipe

### ISSUE THREAD

**Issue by lucianopaz** [conda-forge/pymc-feedstock#101]
### Comment:

Referencing https://github.com/pymc-devs/pytensor/issues/515, we caught a potential regression on Windows systems where MKL would not have been detected automatically in order to set the default blas ldflags. We should add a test to the `pytensor` full recipe that simply runs this assert:

```bash
python -c 'import pytensor; assert pytensor.config.blas__ldflags != "", "Blas flags are empty"'
```

The reason for adding a test and not relying on the warning is that we might remove the warning altogether in the future, once the other `pytensor` backends catch up to the C backend.

Tagging @maresb

**Comment by maresb** [comment]
Added in https://github.com/conda-forge/pytensor-suite-feedstock/pull/74/commits/2cd65cf4f9183e3a9e9f6ca0fc2e0277579c43a6

**Comment by maresb** [comment]
Completed in https://github.com/conda-forge/pytensor-suite-feedstock/pull/76
