### ISSUE TITLE
`pymc` vs `pymc-base`

### ISSUE THREAD

**Issue by renan-r-santos** [conda-forge/pymc-feedstock#107]
### Comment:

When should we use `pymc-base` instead of `pymc`?

I also see there's also `pytensor-base` and `pytensor`. Should `pymc-base` depend on `pytensor-base` instead of `pytensor`?

The reason why I'm asking this second question is that it seems `pytensor-base` doesn't have a compiler as runtime dependency and that would be nice for my use case, because right now, installing either `pymc` or `pymc-base` brings `GCC` and it shadows my `Clang` installation under Linux.

**Comment by maresb** [comment]
> The reason why I'm asking this second question is that it seems `pytensor-base` doesn't have a compiler as runtime dependency and that would be nice for my use case, because right now, installing either `pymc` or `pymc-base` brings `GCC` and it shadows my `Clang` installation under Linux.

Hey @renan-r-santos, I don't know why I didn't see your message sooner, but you're absolutely right! I made a mistake in f871e556ad2b41c945cca6d1c8fb4b6a0cf86dd0. Thanks for pointing this out, I will fix it for v5.11.0.
