### ISSUE TITLE
Have pymc-base depend on aesara-base

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pymc-feedstock#46]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Now that there's an aesara-base that installs without compilers, we can have `pymc-base` just depend on that and have a clean `pymc` package that way. https://github.com/conda-forge/aesara-feedstock/pull/77

CC @maresb

### Installed packages

```shell
foo
```

### Environment info

```shell
foo
```

**Comment by maresb** [comment]
The new `aesara-base` package exists only for 2.7.4, but the current version of pymc pins strictly to 2.7.3.

How hard would it be to cut a new patch release of pymc to depend on Aesara 2.7.4? Or I could just prepare the recipe and we wait for the next scheduled pymc release.

**Comment by twiecki** [comment]
We just released a new version but could easily do a patch for `2.7.4`, but also fine to prepare that now for when it's ready.

**Comment by twiecki** [comment]
PR to bump the pymc version: https://github.com/pymc-devs/pymc/pull/5947

**Comment by maresb** [comment]
Oh, I thought you meant that you "just released" a new version a week ago, but now I see that it was 2 hours ago. :joy:

**Comment by twiecki** [comment]
No time like the present ;).

**Comment by maresb** [comment]
@twiecki I think we're prepared.

We can merge #47 into main once it passes. (Good thing you hadn't added the `automerge` label because I forgot to rerender. :facepalm:  All good now though, assuming it passes, which it will.)

And then once the autotick-bot creates the PR for v4.1.1 we can merge #49 into that PR and achieve world peace. :smile:

**Comment by maresb** [comment]
Closed by #53
