### ISSUE TITLE
Package 5.2.0 can't be installed

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pymc-feedstock#77]
### Comment:

On OSX: `mamba install pymc==5.2.0` 
```
 - package pymc-5.2.0-hd8ed1ab_0 requires pymc-base 5.2.0 pyhd8ed1ab_0, but none of the providers can be installed
 - ```

CC @maresb

**Comment by ocefpaf** [comment]
Can you try again? Maybe the package was not available yet when you tried. I don't have a mac but I tried a dry-run in a mock env and I could see it there:

```
CONDA_SUBDIR=osx-64 conda create --name TEST "pymc=5.2.0"  --dry-run
```

**Comment by twiecki** [comment]
Still doesn't work.

**Comment by ocefpaf** [comment]
> Huh, that seems to work. Weird. Is my env borked?

You probably have packages that are not compatible with the pymc 5.2.0 dependencies. If you have `mamba` you can try this on your `.condarc` to see better error messages on the conflicts:

```
experimental_sat_error_message: true
```
