### ISSUE TITLE
Could this package be re-rendered for Python 3.7?

### ISSUE THREAD

**Issue by jchodera** [conda-forge/pymc-feedstock#8]
A py37 version of this package has not yet been built and pushed to conda-forge.

**Comment by Lnaden** [comment]
I wanted to nudge this issue. I can't quite tell from the main repo, but is this Python 3.7 compatible now? If so, could this recipe be updated to include it (and maybe 3.8 as well).

**Comment by fonnesbeck** [comment]
We are encouraging users to move to PyMC3. However, we would welcome a PR if someone really wants this to happen.

**Comment by ocefpaf** [comment]
Please discuss that upstream. There is nothing we can do here in the conda-forge package.
